### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by Crytilis** [Uniswap/interface#2618] opened 2021-10-15 00:12 UTC
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at df (https://app.uniswap.org/static/js/main.411b0c26.chunk.js:1:330271)
    at ua (https://app.uniswap.org/static/js/35.a759c04b.chunk.js:2:1189950)
    at Ha (https://app.uniswap.org/static/js/35.a759c04b.chunk.js:2:1199517)
    at Ku (https://app.uniswap.org/static/js/35.a759c04b.chunk.js:2:1243241)
    at Ps (https://app.uniswap.org/static/js/35.a759c04b.chunk.js:2:1229491)
    at js (https://app.uniswap.org/static/js/35.a759c04b.chunk.js:2:1229419)
    at Ss (https://app.uniswap.org/static/js/35.a759c04b.chunk.js:2:1229282)
    at bs (https://app.uniswap.org/static/js/35.a759c04b.chunk.js:2:1226248)
    at https://app.uniswap.org/static/js/35.a759c04b.chunk.js:2:1175742
    at https://app.uniswap.org/static/js/35.a759c04b.chunk.js:2:1252979
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.81",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.81"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment] 2021-10-18 17:12
thanks! dupe of https://github.com/Uniswap/interface/issues/2498

**Closed by willhennessy** 2021-10-18 17:12 UTC
