### ISSUE TITLE
Crash report: `Error: STRINGPREP_CONTAINS_UNASSIGNED`

### ISSUE THREAD

**Issue by mattbloom** [Uniswap/interface#2918] opened 2021-12-02 21:35 UTC
## URL
  
https://app.uniswap.org/#/pool

## Error

```
Error: STRINGPREP_CONTAINS_UNASSIGNED
```

## Stacktrace

```
Error: STRINGPREP_CONTAINS_UNASSIGNED
    at https://app.uniswap.org/static/js/34.92d1da43.chunk.js:2:1137823
    at Array.forEach (<anonymous>)
    at y (https://app.uniswap.org/static/js/34.92d1da43.chunk.js:2:1137786)
    at k (https://app.uniswap.org/static/js/34.92d1da43.chunk.js:2:1138427)
    at https://app.uniswap.org/static/js/main.eaaf5798.chunk.js:1:374312
    at En (https://app.uniswap.org/static/js/main.eaaf5798.chunk.js:1:374537)
    at ua (https://app.uniswap.org/static/js/34.92d1da43.chunk.js:2:1249373)
    at Ha (https://app.uniswap.org/static/js/34.92d1da43.chunk.js:2:1258940)
    at $u (https://app.uniswap.org/static/js/34.92d1da43.chunk.js:2:1302664)
    at Ps (https://app.uniswap.org/static/js/34.92d1da43.chunk.js:2:1288914)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by mattbloom** [comment] 2021-12-03 03:12
I cannot trade or do anything until this is fixed

**Comment by FortisFortuna** [comment] 2021-12-03 16:49
Getting the same error. Works fine when metamask isn't connected

**Comment by FortisFortuna** [comment] 2021-12-03 17:38
duplicate of https://github.com/Uniswap/interface/issues/2888

**Comment by FortisFortuna** [comment] 2021-12-03 17:39
https://github.com/Uniswap/interface/issues/2895
https://github.com/Uniswap/interface/issues/2892
https://github.com/Uniswap/interface/issues/2880
https://github.com/Uniswap/interface/issues/2876

**Comment by NoahZinsmeister** [comment] 2021-12-03 20:51
closing in favor of #2876

**Closed by NoahZinsmeister** 2021-12-03 20:51 UTC

**Comment by mattbloom** [comment] 2021-12-03 21:29
I can confirm the emoji in the ENS domain is tripping up Uniswap app. I switched ENS domain to a non-emojie one and it works fine now. Thanks for the help on this @NoahZinsmeister
