### ISSUE TITLE
Second scroll bar in "Manage" modal doesn't look good

### ISSUE THREAD

**Issue by samuveth** [Uniswap/interface#2639] opened 2021-10-19 06:50 UTC
![image](https://user-images.githubusercontent.com/51686767/137858221-4dbb4650-fa6a-4dff-8947-7b4595c3ac41.png)

**Comment by moodysalem** [comment] 2021-10-19 16:56
agree, duplicate of https://github.com/Uniswap/interface/issues/1945

we would love a pr!

**Closed by moodysalem** 2021-10-19 16:56 UTC
Labels: bug
