### ISSUE TITLE
Crash report: `Error: Invalid token address: 0xc5102fE9359FD9a28f877a67E36B0F050d81a3cc`

### ISSUE THREAD

**Issue by 0xAlex6** [Uniswap/interface#3934] opened 2022-06-17 07:19 UTC
## URL
  
https://app.uniswap.org/#/swap?chain=mainnet

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: Invalid token address: 0xc5102fE9359FD9a28f877a67E36B0F050d81a3cc
```

## Stacktrace

```
Error: Invalid token address: 0xc5102fE9359FD9a28f877a67E36B0F050d81a3cc
    at e.get (https://app.uniswap.org/static/js/main.2ce6a487.chunk.js:1:507323)
    at https://app.uniswap.org/static/js/main.2ce6a487.chunk.js:1:670613
    at Object.Ta [as useMemo] (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2759031)
    at t.useMemo (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2668610)
    at S (https://app.uniswap.org/static/js/main.2ce6a487.chunk.js:1:670321)
    at Oe (https://app.uniswap.org/static/js/main.2ce6a487.chunk.js:1:633351)
    at fa (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2754298)
    at za (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2763865)
    at Yf (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2807589)
    at Cs (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2793839)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "102.0.0.0",
    "major": "102"
  },
  "engine": {
    "name": "Blink",
    "version": "102.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by kayleegeorge** [comment] 2022-06-17 15:44
Closing this as it's a duplicate of issue https://github.com/Uniswap/interface/issues/3904 and it's being fixed right now!

**Comment by kayleegeorge** [comment] 2022-06-17 15:44
Closing this as it's a duplicate of issue https://github.com/Uniswap/interface/issues/3904 and it's being fixed right now!

**Closed by kayleegeorge** 2022-06-17 15:44 UTC
