### ISSUE TITLE
Issues on USDT approvals on Ethereum mainnet (incorrect reset step)

### ISSUE THREAD

**Issue by Nanyan** [Uniswap/interface#7083] opened 2023-08-04 06:43 UTC
**Bug Description**
For an address which have successfully approved the USDT (on Ethereum miannet) to de `Permit2` contract( 0x000000000022D473030F116dDEE9F6B43aC78BA3) , and then it did not send a swap transaction immediately, for example, stop operation for several hours or close the browser, and then open the uniswap web site, and try to swap the USDT again, then  It requires a reseting of USDT approval , even though the allowance is large enough for the swap!

may be it should be a bug, since I think it's unnecessary to do a re-approval.

**Steps to Reproduce**

I'm not sure the follows steps will absolutely reproduce this issue.

1. For an address do an approval, like this : https://etherscan.io/tx/0xae44fad94ecfb9e50abe65eaa9a3976561655c37bce168d29f6a02de3c5058bd
2. Then close the dapp, or just wait several hours and then refresh the web,
3. Try to swap USDT for others tokens again, then it requires a reseting usdt approval.

**Expected Behavior**

It's no need to reset USDT approval when the allowance is enough.

**Additional Context**
![image](https://github.com/Uniswap/interface/assets/1623062/19b5c841-71aa-4aa1-bb9b-7a7a55aee178)

![image](https://github.com/Uniswap/interface/assets/1623062/15155e79-68d7-4791-93fc-f18924ceacc9)

**Comment by kevinho** [comment] 2023-08-04 10:27
The (SINOHOPE)[https://sinohope.com] team is developing a crypto wallet based on MPC-TSS technology with multi-signature feature. 
Since its launch 3 months ago, we have nearly 1B USD in AUM and over 100 corporate clients. In line with customer needs, we are one of the few that offer complete DApp browser functionality within our MPC wallet.

Uniswap is foundational to the decentralized world and is the DApp most favored by our users. During the implementation of the DApp browser, we have primarily used the Uniswap DApp for testing.

Due to the existence of multi-signature scenarios, users need to exit the DApp (**close webview**) to carry out the approval process. This behavior results in a life cycle for the DApp within our built-in browser that is very different from that in single-signature wallets (such as Metamask Mobile). It may be this specific scenario difference that has **increased the occurrence of the aforementioned bug.**

The Sinohope team is willing to collaborate with the Uniswap team, offering all kinds of conditions to assist in fixing this problem and helping Uniswap expand to a larger scale of customers.

**Comment by just-toby** [comment] 2023-08-07 19:32
@Nanyan thanks for the report. i can't reproduce this issue personally. can you confirm that you are setting the initial USDT approval through our webapp too? in my testing, the approval was properly recognized in the subsequent swap and it did not try to reset.

**Comment by Nanyan** [comment] 2023-08-08 08:12
@just-toby Yes I was only using the https://app.uniswap.org/#/swap to set the approval and encountered the issue.

**Comment by Nanyan** [comment] 2023-08-08 08:49
Some debug information may be helpful to you.

When the code running into the `generateRequiredSteps` function in the `/interface/src/components/swap/ConfirmSwapModal.tsx` file, some variables's value are as follow:
- `allowance.state` : `AllowanceState.REQUIRED`
- `allowance.allowedAmount` : (I can't see the detail amount, but it's greater then 0. I saw it has 8 bytes of `-1`, I don't know how the javascript represents a big integer, the actually amount should be 32 bytes 0xff )
- `allowance.needsSetupApproval` : false
- `allowance.needsPermitSignature` : true

Why one of the  following condition is `allowance.allowedAmount.greaterThan(0)` ? 
```javascript
    if (
      allowance.state === AllowanceState.REQUIRED &&
      allowance.token.equals(USDT_MAINNET) &&
      allowance.allowedAmount.greaterThan(0)
    ) {
      steps.push(ConfirmModalState.RESETTING_USDT)
    }
```
Or may be we should add one more condition as follows:
```javascript
    if (
      allowance.state === AllowanceState.REQUIRED &&
      allowance.token.equals(USDT_MAINNET) &&
      allowance.allowedAmount.greaterThan(0) &&
      allowance.needsSetupApproval
    ) {
      steps.push(ConfirmModalState.RESETTING_USDT)
    }
```

**Comment by just-toby** [comment] 2023-08-23 20:50
@Nanyan sorry for the delay here - you're right with that last suggestion there. i'll push a fix asap. thanks so much for debugging !

**Comment by Jdecristi** [comment] 2023-09-06 23:09
Hey @just-toby @natew, Can we close this Issue since you added and merged this PR? Thanks

**Closed** 2023-09-06 23:09 UTC
Labels: bug
