### ISSUE TITLE
Proposal status layout bug

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/interface#1904] opened 2021-06-23 20:39 UTC
On Google Chrome mobile browse on Android

Expected behavior: the status (Active, Executed, Defeated) should be a fixed width that contains the text. Only the width of the proposal title should shrink.

![Screenshot_20210623-163531](https://user-images.githubusercontent.com/5455577/123164728-55a87c00-d441-11eb-8aa7-40ac68471a66.png)

**Comment by julianjca** [comment] 2021-06-28 08:08
hi @willhennessy ,
I tried to fix this bug with the above PR.
I've tried testing on my android device but found no luck, those bugs did not appear on mine.

can you try this Vercel deployment to check whether this fix is working as intended?
https://uniswap-interface-git-fork-julianjca-fix-proposa-d072f9-uniswap.vercel.app/#/vote

**Comment by willhennessy** [comment] 2021-06-28 14:07
Looks good to me! I notice the create proposal button is also pushed down one line. Can you align it with the title?
![Screenshot_20210628-100456](https://user-images.githubusercontent.com/5455577/123650529-a977e400-d7f8-11eb-98c8-64b7ff38f841.png)

**Comment by julianjca** [comment] 2021-06-29 02:04
@willhennessy I just fixed the layout for mobile for that also on my latest commit.
can you confirm?
https://uniswap-interface-git-fork-julianjca-fix-proposa-d072f9-uniswap.vercel.app/#/vote

<img width="386" alt="Screen Shot 2021-06-29 at 09 03 20" src="https://user-images.githubusercontent.com/27475885/123725801-f3c09a00-d8b8-11eb-95d4-15be975aab67.png">

**Comment by willhennessy** [comment] 2021-06-29 03:04
It looks perfect! Awesome 
![Screenshot_20210628-230354](https://user-images.githubusercontent.com/5455577/123730933-33f62d00-d865-11eb-9549-4dbb0e17fcaa.png)

**Comment by julianjca** [comment] 2021-06-29 03:05
@willhennessy awesome!
what's the next step for this?
it's my first PR so I'm not sure yet.

**Comment by willhennessy** [comment] 2021-06-29 03:13
Let's do it! You can submit a PR following these instructions: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Submit it to the `main` branch in this repo (uniswap-interface)

After that, one of our engineers will review it

**Comment by julianjca** [comment] 2021-06-29 03:15
Nice.
I've created a PR for this here.
https://github.com/Uniswap/uniswap-interface/pull/1919

Thanks @willhennessy !

**Comment by julianjca** [comment] 2021-07-13 06:09
Hi @willhennessy want to do a follow up to the PR.
it seem's like it has not been reviewed / merged yet
https://github.com/Uniswap/uniswap-interface/pull/1919/
thanks!

**Closed** 2021-12-01 15:23 UTC
Labels: bug, good first issue, p2
